language: scala
jdk: openjdk8
scala: 2.12.8

jobs:
  include:
    - stage: check
      script: sbt scalafmtCheckAll || { echo "[error] Unformatted code found. Please run 'scalafmtAll' and commit the reformatted code."; false; }
      name: Code style check (fixed with `sbt scalafmtAll`)
    - script: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
      name: Build code style check (fixed with `sbt scalafmtSbt`)
    - stage: test
      script: sbt test
      name: Run tests
    - script: sbt scripted
      name: Run sbt plugin tests
    - stage: publish
      script: sbt ^publish
      name: Publish artifacts

stages:
  - name: check # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-paradox-apidoc AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "m2cgGJQahaCn2lKg27gG+15zymwGje1XTFULA3JZ1la2A+mpA8c5Eto8ZbNRSRl8zKdzidmaK5OkI4N6jCbhL9x9W4qRVwNiGL/hTluS30PuIyOs7mF+QpcybRPJ6GzXl+ZNTDZ/UfthuOlcXyLw+kpH1j44Egx+oPKTDn5rGbLvj/UZpwaQmT8QcOoXGSD5rOdKyogH+j7jnQNGFfzJ1Dj5UIRFySlTJhlW71eAjYtWdfFUdQ2DlET6TVHGONY6PlZQt8qE/8OQyt+Yr56gNBYLtFjzfKaGXxvQNNvpoxx/FW8rp+cfnp26O3fbkmKBFrw6KtamZVvKMQGmA75A+IC6DaRa32ui5zULCh6Hswf/EVqnmpfNJbRSyBm05fT1KOn5l+XYTcGLPJmnZ+sFKS+VB5z9fVtO7fdnEQzBtn3cKOjrb+zstMBsSZk1CYHLLHcGidh/8CAjbE6/JGlq5q+AlMKN21dlh/TRKx/jfNch8KVJA5gnjlkgfQwOVxpLVYTynlwnLoQuh0369xym4Quy8mLrXWZEV+xxxbRpl3MsGIZkEXvra5vyuK6SwZuk6Rpep6oEf5S5MItn++ZGPlzlXlQLG9AYYSjetXQJqwDDewYchGZQf1xYRYLjOoX9Fz5yfEw/V1Ew3eUTDJez+mInY3ykg6rscLD+dBM8d94="
    # travis encrypt BINTRAY_PASS=...
    - secure: "Q1ZCY7+kfR99nPzxEmDWxaexHBE4z+Q0cGq+bEwszPfDoajYzm1XPkFUBWBCv1aqamot4UZTRaNECG9q8GRswHhwwNhg9+6oZOki6n5YdS3N+R9ozbTOI5p/SBzbVpMs+CH6MMN8uOjQSzCseo1h92iVm79Bs3/A2Y/XWCrFYNTQ/gsVvzM9Ftd1mCkZUQ9mzaPYkVTWHjvDgpeUo3E/4c63TjYuw+K2dEHT25sgNxrptfY/MM1Hw2BRBlaxKl49FM80MRWItAPMeunE9FLjVXaa0l69j1YjmPyKXAngwTyYhMobvjTpsV85SCBvzdCDkBZb5NP0SeXQDU7kpbzEZ1osRswFsaBqrA3RLGA98YtNFw3V5jWucF7xdSTWIdy+92iCnqFJqtcZsdRO8uzLrscceqaGiUsT1idYSlo+8OwOlAzmILbfjjDhhqpkzp0Nuib+afna6FjUgbAaFbNg3x0nw8kZOgXC6Or/5gFPJUePpcr6Bzaq5zsIo7DXK74vIVV8WTWSee/3kWaOFh5jIvuoJQ05Fjk6pKRhsBE35UD5NR7aDbnzuhB3BWXysOio6x594UeS4R5TkLtuKMTOV5+trJ84yLJCbpDiUspgPjgFeXlN49x/bPc8qyIPKMunPSSI2iF4hCooW0a/dbo7L/HTkpOSIkqqPwaP6lbyxzw="
